# Generated by Django 5.1.1 on 2024-10-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videochunkedupload',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
