# Generated by Django 5.1.1 on 2024-10-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_videochunkedupload_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videochunkedupload',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='videochunkedupload',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='videochunkedupload',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='videochunkedupload',
            name='offset',
        ),
        migrations.RemoveField(
            model_name='videochunkedupload',
            name='status',
        ),
        migrations.RemoveField(
            model_name='videochunkedupload',
            name='user',
        ),
        migrations.AddField(
            model_name='videochunkedupload',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videochunkedupload',
            name='file',
            field=models.FileField(default=None, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videochunkedupload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
